name: contextions
description: A Flutter package that adds extension methods on BuildContext for easy access to Navigator, Theme, and MediaQuery functions.
version: 0.0.1
homepage: https://github.com/plokmij/contextions

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0